In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./Resources/diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
y = df["Outcome"]
X = df.drop(columns="Outcome")

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200,
   random_state=1)

In [8]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
y_pred

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [11]:
y_test

118    0
132    1
3      0
693    1
654    0
      ..
427    1
135    0
501    0
392    0
367    0
Name: Outcome, Length: 192, dtype: int64

In [12]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
610,3,106,54,21,158,30.9,0.292,24
681,0,162,76,36,0,49.6,0.364,26
706,10,115,0,0,0,0.0,0.261,30
281,10,129,76,28,122,35.9,0.280,39
625,4,90,88,47,54,37.7,0.362,29
...,...,...,...,...,...,...,...,...
214,9,112,82,32,175,34.2,0.260,36
137,0,93,60,25,92,28.7,0.532,22
645,2,157,74,35,440,39.4,0.134,30
17,7,107,74,0,0,29.6,0.254,31
746,1,147,94,41,0,49.3,0.358,27

In [13]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
118,4,97,60,23,0,28.2,0.443,22
132,3,170,64,37,225,34.5,0.356,30
3,1,89,66,23,94,28.1,0.167,21
693,7,129,68,49,125,38.5,0.439,43
654,1,106,70,28,135,34.2,0.142,22
...,...,...,...,...,...,...,...,...
427,1,181,64,30,180,34.1,0.328,38
135,2,125,60,20,140,33.8,0.088,31
501,3,84,72,32,0,37.2,0.267,28
392,1,131,64,14,415,23.7,0.389,21
367,0,101,64,17,0,21.0,0.252,21

In [14]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.7760416666666666

In [15]:
log(probability of admission/(1 - probability of admission))

SyntaxError: invalid syntax (3116867718.py, line 1)